[package]
name = "lottery_contract"
version = "0.1.0"
edition = "2021"
authors = ["Akileus"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-sdk = "4.0.0"
near-contract-standards = "4.0.0"

[lib]
crate-type = ["cdylib", "rlib"]